/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as linea from "./linea";
export type { linea };
import type * as polygonZkEvm from "./polygonZkEVM";
export type { polygonZkEvm };
