/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface BaseReceiverUnifySafeModuleInterface extends utils.Interface {
  functions: {
    "originSender()": FunctionFragment;
    "safe()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "originSender" | "safe"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "originSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "safe", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "originSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safe", data: BytesLike): Result;

  events: {};
}

export interface BaseReceiverUnifySafeModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseReceiverUnifySafeModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    originSender(overrides?: CallOverrides): Promise<[string]>;

    safe(overrides?: CallOverrides): Promise<[string]>;
  };

  originSender(overrides?: CallOverrides): Promise<string>;

  safe(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    originSender(overrides?: CallOverrides): Promise<string>;

    safe(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    originSender(overrides?: CallOverrides): Promise<BigNumber>;

    safe(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    originSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    safe(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
