/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface PZkVMReceiverUnifySafeModuleInterface extends utils.Interface {
  functions: {
    "onMessageReceived(address,uint32,bytes)": FunctionFragment;
    "originSender()": FunctionFragment;
    "polygonZkEVMBridge()": FunctionFragment;
    "safe()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "onMessageReceived"
      | "originSender"
      | "polygonZkEVMBridge"
      | "safe"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "onMessageReceived",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "originSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "polygonZkEVMBridge",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "safe", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "onMessageReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "originSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polygonZkEVMBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safe", data: BytesLike): Result;

  events: {};
}

export interface PZkVMReceiverUnifySafeModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PZkVMReceiverUnifySafeModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    onMessageReceived(
      originAddress_: PromiseOrValue<string>,
      originNetwork_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    originSender(overrides?: CallOverrides): Promise<[string]>;

    polygonZkEVMBridge(overrides?: CallOverrides): Promise<[string]>;

    safe(overrides?: CallOverrides): Promise<[string]>;
  };

  onMessageReceived(
    originAddress_: PromiseOrValue<string>,
    originNetwork_: PromiseOrValue<BigNumberish>,
    data_: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  originSender(overrides?: CallOverrides): Promise<string>;

  polygonZkEVMBridge(overrides?: CallOverrides): Promise<string>;

  safe(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    onMessageReceived(
      originAddress_: PromiseOrValue<string>,
      originNetwork_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    originSender(overrides?: CallOverrides): Promise<string>;

    polygonZkEVMBridge(overrides?: CallOverrides): Promise<string>;

    safe(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    onMessageReceived(
      originAddress_: PromiseOrValue<string>,
      originNetwork_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    originSender(overrides?: CallOverrides): Promise<BigNumber>;

    polygonZkEVMBridge(overrides?: CallOverrides): Promise<BigNumber>;

    safe(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    onMessageReceived(
      originAddress_: PromiseOrValue<string>,
      originNetwork_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    originSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    polygonZkEVMBridge(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safe(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
