/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMessageService } from "./IMessageService";
export type { MessageServiceBase } from "./MessageServiceBase";
