/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMessageService__factory } from "./IMessageService__factory";
export { MessageServiceBase__factory } from "./MessageServiceBase__factory";
