/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  BaseReceiverUnifySafeModule,
  BaseReceiverUnifySafeModuleInterface,
} from "../../../contracts/receiverModules/BaseReceiverUnifySafeModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract GnosisSafe",
        name: "safe_",
        type: "address",
      },
      {
        internalType: "address",
        name: "originSender_",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "originSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "safe",
    outputs: [
      {
        internalType: "contract GnosisSafe",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526040516101873803806101878339810160408190526100229161006b565b600080546001600160a01b039384166001600160a01b031991821617909155600180549290931691161790556100a5565b6001600160a01b038116811461006857600080fd5b50565b6000806040838503121561007e57600080fd5b825161008981610053565b602084015190925061009a81610053565b809150509250929050565b60d4806100b36000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063186f03541460375780632b59241f14607f575b600080fd5b60005460569073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60015460569073ffffffffffffffffffffffffffffffffffffffff168156fea26469706673582212209061f9bc403309e8158db29de41cd2b33603adb3616229d1ca46ec3f84ed3c7764736f6c63430008130033";

type BaseReceiverUnifySafeModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BaseReceiverUnifySafeModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BaseReceiverUnifySafeModule__factory extends ContractFactory {
  constructor(...args: BaseReceiverUnifySafeModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    safe_: PromiseOrValue<string>,
    originSender_: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<BaseReceiverUnifySafeModule> {
    return super.deploy(
      safe_,
      originSender_,
      overrides || {}
    ) as Promise<BaseReceiverUnifySafeModule>;
  }
  override getDeployTransaction(
    safe_: PromiseOrValue<string>,
    originSender_: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(safe_, originSender_, overrides || {});
  }
  override attach(address: string): BaseReceiverUnifySafeModule {
    return super.attach(address) as BaseReceiverUnifySafeModule;
  }
  override connect(signer: Signer): BaseReceiverUnifySafeModule__factory {
    return super.connect(signer) as BaseReceiverUnifySafeModule__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BaseReceiverUnifySafeModuleInterface {
    return new utils.Interface(_abi) as BaseReceiverUnifySafeModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseReceiverUnifySafeModule {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BaseReceiverUnifySafeModule;
  }
}
